VERIFIERS="2ls aprove brick cbmc coveriteam-verifier-algo-selection coveriteam-verifier-parallel-portfolio cpa-bam-bnb cpa-bam-smg cpa-lockator cpachecker crux cseq dartagnan deagle divine ebf esbmc-incr esbmc-kind frama-c-sv gazer-theta goblint graves infer korn lart lazycseq locksmith pesco pinaka predatorhp sesl smack symbiotic theta uautomizer ugemcutter ukojak utaipan veriabs verifuzz coastal gdart java-ranger jayhorn jbmc jdart spf ";

CATEGORIES="unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-data-race.NoDataRace-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-BitVectors termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety unreach-call.SoftwareSystems-BusyBox-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java ";

VERIFIERSLIST=(
"ReachSafety: 2ls cbmc coveriteam-verifier-algo-selection coveriteam-verifier-parallel-portfolio cpachecker crux divine esbmc-kind goblint graves infer lart pesco pinaka symbiotic theta uautomizer ukojak utaipan veriabs verifuzz "
"MemSafety: 2ls cbmc coveriteam-verifier-parallel-portfolio cpa-bam-smg cpachecker divine esbmc-kind goblint graves pesco predatorhp sesl symbiotic uautomizer ukojak utaipan verifuzz "
"ConcurrencySafety: 2ls cbmc coveriteam-verifier-algo-selection coveriteam-verifier-parallel-portfolio cpa-lockator cpachecker cseq dartagnan deagle divine ebf esbmc-incr esbmc-kind goblint graves infer lazycseq pesco symbiotic theta uautomizer ugemcutter ukojak utaipan verifuzz "
"NoOverflows: 2ls cbmc coveriteam-verifier-parallel-portfolio cpachecker crux divine esbmc-kind frama-c-sv goblint graves infer pesco pinaka symbiotic uautomizer ukojak utaipan verifuzz "
"Termination: 2ls aprove cbmc coveriteam-verifier-parallel-portfolio cpachecker divine esbmc-kind goblint graves pesco pinaka symbiotic uautomizer ukojak utaipan verifuzz "
"SoftwareSystems: 2ls cbmc coveriteam-verifier-parallel-portfolio cpa-bam-bnb cpa-bam-smg cpachecker divine esbmc-kind goblint graves infer lart pesco smack symbiotic uautomizer ukojak utaipan verifuzz "
"Overall: 2ls cbmc coveriteam-verifier-parallel-portfolio cpachecker divine esbmc-kind goblint graves pesco symbiotic uautomizer ukojak utaipan "
"FalsificationOverall: 2ls cbmc coveriteam-verifier-parallel-portfolio cpachecker divine esbmc-kind graves pesco symbiotic uautomizer ukojak utaipan verifuzz "
"JavaOverall: coastal gdart java-ranger jayhorn jbmc jdart spf "
)

CATEGORIESLIST=(
"ReachSafety: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations "
"MemSafety: valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet "
"ConcurrencySafety: unreach-call.ConcurrencySafety-Main "
"NoOverflows: no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other "
"Termination: termination.Termination-BitVectors termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other "
"SoftwareSystems: unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety unreach-call.SoftwareSystems-BusyBox-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety "
"JavaOverall: assert_java.ReachSafety-Java "
"FalsificationOverall: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-BitVectors termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety unreach-call.SoftwareSystems-BusyBox-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java "
"Overall: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-BitVectors termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety unreach-call.SoftwareSystems-BusyBox-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java "
)


