VERIFIERS="2ls brick cbmc cpa-bam-bnb cpa-lockator cpa-seq dartagnan divine esbmc-incr esbmc-kind frama-c-sv gazer-theta goblint korn lazycseq pesco pinaka predatorhp smack symbiotic uautomizer ukojak utaipan veriabs coastal java-ranger jayhorn jbmc jdart spf ";

CATEGORIES="unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-data-race.NoDataRace-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java ";

VERIFIERSLIST=(
"ReachSafety: 2ls cbmc cpa-seq divine esbmc-kind goblint pesco pinaka symbiotic uautomizer ukojak utaipan veriabs "
"MemSafety: 2ls cbmc cpa-seq divine esbmc-kind pesco predatorhp symbiotic uautomizer ukojak utaipan "
"ConcurrencySafety: 2ls cbmc cpa-seq cpa-lockator dartagnan divine esbmc-incr esbmc-kind lazycseq goblint pesco symbiotic uautomizer ukojak utaipan "
"NoOverflows: 2ls cbmc cpa-seq divine esbmc-kind frama-c-sv goblint pesco pinaka symbiotic uautomizer ukojak utaipan "
"Termination: 2ls cbmc cpa-seq divine esbmc-kind pesco pinaka symbiotic uautomizer ukojak utaipan "
"SoftwareSystems: 2ls cbmc cpa-bam-bnb cpa-seq divine esbmc-kind goblint pesco smack symbiotic uautomizer ukojak utaipan "
"Overall: 2ls cbmc cpa-seq divine esbmc-kind pesco symbiotic uautomizer ukojak utaipan "
"FalsificationOverall: 2ls cbmc cpa-seq divine esbmc-kind pesco symbiotic uautomizer ukojak utaipan "
"JavaOverall: coastal java-ranger jayhorn jbmc jdart spf "
)

CATEGORIESLIST=(
"ReachSafety: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations "
"MemSafety: valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet "
"ConcurrencySafety: unreach-call.ConcurrencySafety-Main "
"NoOverflows: no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other "
"Termination: termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other "
"SoftwareSystems: unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety "
"JavaOverall: assert_java.ReachSafety-Java "
"FalsificationOverall: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java "
"Overall: unreach-call.ReachSafety-Arrays unreach-call.ReachSafety-BitVectors unreach-call.ReachSafety-ControlFlow unreach-call.ReachSafety-ECA unreach-call.ReachSafety-Floats unreach-call.ReachSafety-Heap unreach-call.ReachSafety-Loops unreach-call.ReachSafety-ProductLines unreach-call.ReachSafety-Recursive unreach-call.ReachSafety-Sequentialized unreach-call.ReachSafety-XCSP unreach-call.ReachSafety-Combinations valid-memsafety.MemSafety-Arrays valid-memsafety.MemSafety-Heap valid-memsafety.MemSafety-LinkedLists valid-memsafety.MemSafety-Other valid-memcleanup.MemSafety-MemCleanup valid-memsafety.MemSafety-Juliet unreach-call.ConcurrencySafety-Main no-overflow.NoOverflows-BitVectors no-overflow.NoOverflows-Other termination.Termination-MainControlFlow termination.Termination-MainHeap termination.Termination-Other unreach-call.SoftwareSystems-AWS-C-Common-ReachSafety valid-memsafety.SoftwareSystems-BusyBox-MemSafety no-overflow.SoftwareSystems-BusyBox-NoOverflows unreach-call.SoftwareSystems-DeviceDriversLinux64-ReachSafety unreach-call.SoftwareSystems-DeviceDriversLinux64Large-ReachSafety valid-memsafety.SoftwareSystems-OpenBSD-MemSafety valid-memsafety.SoftwareSystems-uthash-MemSafety no-overflow.SoftwareSystems-uthash-NoOverflows unreach-call.SoftwareSystems-uthash-ReachSafety assert_java.ReachSafety-Java "
)


